Added Properties
Kanyelings/linked_list pull request #25
Opened 2022-04-05 11:34 UTC by mofirojean

fixes #7 
Created a node class
Added some linked list property in the LinkedList class
Changed the zero in the size() method and assigned it the Size property

2022-04-05 11:44 UTC, kimbifavour commented
You've not added the node class.

2022-04-05 11:45 UTC, kimbifavour requested changes
Add the node class

2022-04-05 11:52 UTC, kimbifavour approved these changes

2022-04-05 11:53 UTC, kimbifavour approved these changes

2022-04-06 11:37 UTC, elroykanye requested changes
Looks good, but not very.
You may have to check out the meanings of various access modifiers and their example use cases so you know when and how to use what. 😊

2022-04-06 11:37 UTC, elroykanye commented on src/com/kanyelings/LinkedListImpl.java
> +        return size;
size is not a private property. I don't see the need for a a method that returns it again. That's redundancy.

Also, size could be easily accessed and modified in an object causing it not to reflect the true nature of the list.

2022-04-07 11:01 UTC, mofirojean commented on src/com/kanyelings/LinkedListImpl.java
> +        return size;
Kanye i don't quite understand, please can you explain

2022-04-07 11:03 UTC, elroykanye commented on src/com/kanyelings/LinkedListImpl.java
> +        return size;
Do some research on getters and setters.

Remember, this is java not python.

2022-04-08 21:14 UTC, elroykanye commented
Are you still working on this?

2022-04-11 20:47 UTC, mofirojean commented on src/com/kanyelings/LinkedListImpl.java
> +        return size;
Ok

2022-04-12 20:49 UTC, elroykanye approved these changes

2022-04-12 20:49 UTC, elroykanye commented on src/com/kanyelings/LinkedListImpl.java
> +        return size;
`very secure` :)

2022-04-12 20:49 UTC, merged

2022-04-12 20:54 UTC, mofirojean commented on src/com/kanyelings/LinkedListImpl.java
> +        return size;
can i delete the branch now

2022-04-12 20:56 UTC, mofirojean commented
Kanye can i now delete the branch?

2022-04-12 21:42 UTC, elroykanye commented on src/com/kanyelings/LinkedListImpl.java
> +        return size;
Depends on you 🙂